name: bluebuild
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
jobs:
  bluebuild:
    name: Bluebuild
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - hosts/lillipup.yml
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          maximize_build_space: true
          recipe: ${{ matrix.recipe }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
